import { useMemo, useState } from 'react';
import { ArrowUpRight, Bot, Check, ChevronDown, Code2, ExternalLink, Gift, Globe2, Layers3, MessageSquareText, Plus, Search, Send, Smartphone, Sparkles, Star, Users, X, Zap } from 'lucide-react';

const seedApps = [
  {id:1,name:'FlowPilot',tagline:'Turn scattered product notes into a clear weekly roadmap.',category:'Productivity',platform:'Live URL',url:'https://example.com',reward:'Free Pro year',feedback:'Need 8 founders to test our first-run planning flow and tell us where it feels too heavy.',count:12,color:'from-emerald-400 to-cyan-400',icon:Layers3},
  {id:2,name:'PromptLayer Studio',tagline:'A visual playground for testing and comparing AI prompts.',category:'AI Tools',platform:'Live URL',url:'https://example.com',reward:'$15 gift card',feedback:'Looking for honest feedback on prompt comparison and version history from AI builders.',count:7,color:'from-violet-400 to-fuchsia-400',icon:Bot},
  {id:3,name:'Shiplog',tagline:'Release notes your users will actually read.',category:'Developer Tools',platform:'Figma',url:'https://figma.com',reward:'Feedback swap',feedback:'Need developers to walk through the GitHub setup prototype and flag unclear permissions.',count:5,color:'from-orange-400 to-rose-400',icon:Code2},
  {id:4,name:'PocketSprint',tagline:'Tiny daily challenges that keep remote teams moving.',category:'Mobile/TestFlight',platform:'TestFlight',url:'https://testflight.apple.com',reward:'Lifetime access',feedback:'Seeking iPhone testers for notification timing, streaks, and the team invite experience.',count:18,color:'from-sky-400 to-indigo-400',icon:Smartphone},
  {id:5,name:'SignalDesk',tagline:'Find the customer conversations that deserve a response.',category:'AI Tools',platform:'Live URL',url:'https://example.com',reward:'$10 gift card',feedback:'Test our inbox triage for 15 minutes and report any miscategorized customer messages.',count:9,color:'from-lime-400 to-emerald-400',icon:Zap},
  {id:6,name:'Proofboard',tagline:'Collect beautiful testimonials without the awkward follow-up.',category:'Web Apps',platform:'Live URL',url:'https://example.com',reward:'Free Pro year',feedback:'We need 5 consultants to test the request-to-publish flow and share where they hesitate.',count:4,color:'from-pink-400 to-amber-300',icon:Sparkles}
];
const filters=['All','Web Apps','AI Tools','Developer Tools','Mobile/TestFlight'];
const Field=({label,children})=><label className="block"><span className="mb-2 block text-sm font-medium text-zinc-300">{label}</span>{children}</label>;
const inputClass='focus-ring w-full rounded-xl border border-white/10 bg-zinc-950 px-4 py-3 text-sm text-white placeholder:text-zinc-600';

function Modal({children,onClose}){return <div className="fixed inset-0 z-50 grid place-items-center bg-black/75 p-4 backdrop-blur-sm" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="glass max-h-[92vh] w-full max-w-xl overflow-auto rounded-3xl shadow-2xl shadow-emerald-950/30"><button onClick={onClose} className="float-right m-5 rounded-full p-2 text-zinc-500 transition hover:bg-white/10 hover:text-white"><X size={20}/></button>{children}</div></div>}
function Stars({value,onChange}){return <div className="flex gap-2">{[1,2,3,4,5].map(n=><button type="button" key={n} onClick={()=>onChange(n)} aria-label={`${n} stars`}><Star size={27} className={n<=value?'fill-amber-300 text-amber-300':'text-zinc-700'} /></button>)}</div>}

export default function App(){
 const [apps,setApps]=useState(seedApps),[filter,setFilter]=useState('All'),[query,setQuery]=useState(''),[posting,setPosting]=useState(false),[testing,setTesting]=useState(null),[posted,setPosted]=useState(false),[thanks,setThanks]=useState(false),[rating,setRating]=useState(0);
 const visible=useMemo(()=>apps.filter(a=>(filter==='All'||a.category===filter)&&`${a.name} ${a.tagline} ${a.feedback}`.toLowerCase().includes(query.toLowerCase())),[apps,filter,query]);
 function submitApp(e){e.preventDefault();const f=new FormData(e.currentTarget);setApps([{id:Date.now(),name:f.get('name'),tagline:f.get('tagline'),url:f.get('url'),category:f.get('category'),platform:'Live URL',reward:f.get('reward'),feedback:f.get('feedback'),count:0,color:'from-emerald-400 to-indigo-400',icon:Sparkles},...apps]);setPosted(true);setTimeout(()=>{setPosting(false);setPosted(false)},1400)}
 function submitFeedback(e){e.preventDefault();setApps(apps.map(a=>a.id===testing.id?{...a,count:a.count+1}:a));setThanks(true)}
 function closeTest(){setTesting(null);setThanks(false);setRating(0)}
 return <div className="min-h-screen bg-[radial-gradient(circle_at_50%_-20%,rgba(16,185,129,.18),transparent_35%)]">
  <nav className="sticky top-0 z-30 border-b border-white/5 bg-zinc-950/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><a className="flex items-center gap-2.5 font-bold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-lg bg-emerald-400 text-zinc-950"><Zap size={18} fill="currentColor"/></span>Stage Zero</a><div className="hidden text-xs font-medium text-zinc-500 md:block">THE FIRST USERS ARE THE HARDEST</div><button onClick={()=>setPosting(true)} className="flex items-center gap-2 rounded-xl bg-emerald-400 px-4 py-2.5 text-sm font-bold text-zinc-950 transition hover:bg-emerald-300"><Plus size={17}/>Post your app</button></div></nav>
  <main className="mx-auto max-w-7xl px-5 pb-20 pt-16"><section className="mb-12 max-w-3xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-1.5 text-xs font-semibold text-emerald-300"><Users size={14}/>Built for founders at day zero</div><h1 className="text-5xl font-bold leading-[1.05] tracking-[-.045em] sm:text-7xl">Find your first <span className="text-emerald-400">believers.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-400">Share what you’re building, get thoughtful feedback from real testers, and return the favor. No audience required.</p></section>
   <section className="glass mb-8 rounded-2xl p-3"><div className="flex flex-col gap-3 lg:flex-row"><div className="relative flex-1"><Search className="absolute left-3.5 top-3.5 text-zinc-600" size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search apps, problems, or feedback requests..." className="focus-ring w-full rounded-xl bg-zinc-950/60 py-3 pl-11 pr-4 text-sm placeholder:text-zinc-600"/></div><div className="flex gap-2 overflow-x-auto pb-1 lg:pb-0">{filters.map(f=><button key={f} onClick={()=>setFilter(f)} className={`whitespace-nowrap rounded-xl px-4 py-3 text-sm font-medium transition ${filter===f?'bg-white text-zinc-950':'text-zinc-400 hover:bg-white/5 hover:text-white'}`}>{f}</button>)}</div></div></section>
   <div className="mb-5 flex items-center justify-between"><h2 className="font-semibold">Ready for testing <span className="ml-1 text-zinc-600">{visible.length}</span></h2><button className="flex items-center gap-1 text-sm text-zinc-500">Newest <ChevronDown size={15}/></button></div>
   {visible.length?<section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{visible.map(app=><article key={app.id} className="glass group flex min-h-[390px] flex-col rounded-2xl p-6 transition duration-300 hover:-translate-y-1 hover:border-white/20"><div className="flex items-start justify-between"><div className={`grid h-12 w-12 place-items-center rounded-xl bg-gradient-to-br ${app.color} text-zinc-950 shadow-lg`}><app.icon size={23}/></div><span className="rounded-full bg-white/5 px-3 py-1 text-[11px] font-semibold text-zinc-400">{app.category}</span></div><h3 className="mt-5 text-xl font-bold tracking-tight">{app.name}</h3><p className="mt-1.5 min-h-12 text-sm leading-6 text-zinc-400">{app.tagline}</p><div className="my-5 border-t border-white/5"/><div className="space-y-3 text-sm"><div className="flex gap-3"><MessageSquareText size={17} className="mt-0.5 shrink-0 text-emerald-400"/><p className="leading-5 text-zinc-300">{app.feedback}</p></div><div className="flex items-center gap-3 text-zinc-400"><Gift size={17} className="text-violet-400"/><span>{app.reward}</span></div></div><div className="mt-auto flex items-end justify-between pt-6"><div><span className="flex items-center gap-1.5 text-xs text-zinc-500"><Globe2 size={14}/>{app.platform}</span><span className="mt-1 block text-[11px] text-zinc-600">{app.count} feedback reports</span></div><button onClick={()=>setTesting(app)} className="flex items-center gap-1.5 rounded-xl bg-white px-4 py-2.5 text-sm font-bold text-zinc-950 transition group-hover:bg-emerald-400">Start testing<ArrowUpRight size={16}/></button></div></article>)}</section>:<div className="glass rounded-3xl py-20 text-center"><Search className="mx-auto mb-4 text-zinc-700" size={38}/><h3 className="text-lg font-semibold">Nothing found yet</h3><p className="mt-2 text-sm text-zinc-500">Try another search or category.</p></div>}
  </main>
  {posting&&<Modal onClose={()=>setPosting(false)}>{posted?<div className="grid min-h-96 place-items-center p-10 text-center"><div><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-400 text-zinc-950"><Check size={30}/></span><h2 className="mt-6 text-2xl font-bold">You’re on the board.</h2><p className="mt-2 text-zinc-400">Your app is now ready for its first testers.</p></div></div>:<form onSubmit={submitApp} className="space-y-5 p-7 pt-3 sm:p-9 sm:pt-3"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-400">Developer submission</p><h2 className="mt-2 text-2xl font-bold">Post your app</h2><p className="mt-2 text-sm text-zinc-500">Be specific. Great requests get great feedback.</p></div><div className="grid gap-4 sm:grid-cols-2"><Field label="App name"><input required name="name" className={inputClass} placeholder="Acme"/></Field><Field label="Tagline"><input required name="tagline" className={inputClass} placeholder="One clear sentence"/></Field></div><Field label="App or staging URL"><input required type="url" name="url" className={inputClass} placeholder="https://"/></Field><Field label="Category"><select name="category" className={inputClass}>{filters.slice(1).map(f=><option key={f}>{f}</option>)}</select></Field><Field label="What specific feedback are you looking for?"><textarea required name="feedback" rows="3" className={inputClass} placeholder="What should testers do, and what should they watch for?"/></Field><Field label="Reward or incentive"><input required name="reward" className={inputClass} placeholder="Free Pro year, $10 gift card..."/></Field><button className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-400 py-3.5 font-bold text-zinc-950 hover:bg-emerald-300">Publish request<Send size={17}/></button></form>}</Modal>}
  {testing&&<Modal onClose={closeTest}>{thanks?<div className="grid min-h-96 place-items-center p-10 text-center"><div><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-400 text-zinc-950"><Check size={30}/></span><h2 className="mt-6 text-2xl font-bold">Feedback sent.</h2><p className="mt-2 text-zinc-400">Thanks for helping {testing.name} get better.</p><button onClick={closeTest} className="mt-7 rounded-xl bg-white px-6 py-3 font-bold text-zinc-950">Back to projects</button></div></div>:<form onSubmit={submitFeedback} className="space-y-5 p-7 pt-3 sm:p-9 sm:pt-3"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-400">Testing {testing.name}</p><h2 className="mt-2 text-2xl font-bold">Share useful feedback</h2><a href={testing.url} target="_blank" rel="noreferrer" className="mt-4 flex items-center justify-between rounded-xl border border-emerald-400/20 bg-emerald-400/10 px-4 py-3 text-sm font-semibold text-emerald-300">Open app in a new tab<ExternalLink size={17}/></a></div><Field label="Overall experience"><Stars value={rating} onChange={setRating}/></Field><Field label="What worked well?"><textarea required rows="3" className={inputClass} placeholder="What felt clear, fast, or delightful?"/></Field><Field label="Where did you get stuck or find bugs?"><textarea required rows="3" className={inputClass} placeholder="Include steps to reproduce if you can."/></Field><Field label="Your email or X handle"><input required className={inputClass} placeholder="For your reward"/></Field><button disabled={!rating} className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-400 py-3.5 font-bold text-zinc-950 disabled:cursor-not-allowed disabled:opacity-40">Submit feedback<Send size={17}/></button></form>}</Modal>}
 </div>
}
